apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: thesorrow
  name: thesorrow_compute_role
  uuid: 82217383-f3ef-4a27-b7eb-ff12faa67d71
  resourceversion: alphav1
  generation: 1337
  creationTimestamp: 2023-11-13T03:53:04-08:00
  deletionTimestamp: 2024-12-29T03:54:53-08:00
  labels: {
    type: human,
    workload_type: aimlautomation,
    orchestration: soar,
    business_need: incident response,
    repo: w8mej
  }
  annotations: {
    owner: thesorrow,
    department: infosec,
    cost center: operations
  }
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, watch, list]
    resourcenames: [""]