#If you don't know how to ceate and run a kubeconfig with the appropriate settings; here are two quick env variables and setup ->
#SECRET_NAME=$(kubectl get serviceaccount thesorrow_compute_serviceaccount -o jsonpath='{.secrets[0].name}')
#TOKEN=$(kubectl get secret $SECRET_NAME -o jsonpath='{.data.token}' | base64 --decode)
#kubectl get secret $SECRET_NAME -o jsonpath='{.data.ca\.crt}' | base64 --decode > ca.crt
apiVersion: v1
kind: Config
preferences:
  colors: true
clusters:
  - name: thesorrow_chiba_city
    cluster:
      certificate-authority: /dev/swap/network/secretz/ca.crt
      server: https://thesorrow.haxx.ninja:60443
      tls-server-name: thesorrow.haxx.ninja
      insecure-skip-tls-verify: false
      proxy-url: https://anycast_carp.ipv6.haxx.ninja
      disable-compression: true  #DisableCompression allows client to opt-out of response compression for all requests to the server. This is useful to speed up requests (specifically lists) when client-server network bandwidth is ample, by saving time on compression (server-side) and decompression (client-side): https://github.com/kubernetes/kubernetes/issues/112296.
users:
  - name: thesorrow
    user:
      client-certificate: /dev/swap/network/secretz/yubi.certificate
      client-key: /dev/swap/network/secretz/yubi.key
      token: $TOKEN
      tokenFile: /dev/swap/network/secretz/yubi_k8s.token
      as: thesorrow
      as-uid: 82217383-f3ef-4a27-b7eb-ff12faa67d71
      as-groups: []
      as-user-extra: gecos information forthcoming
contexts:
  - name: thesorrow-context
    context:
      cluster: thesorrow_chiba_city
      namespace: thesorrow
      user: thesorrow
current-context: thesorrow-context
