- name: Manage User thesorrow
  hosts: all
  become: yes
  tasks:
    - name: Ensure user 'thesorrow' exists
      user:
        name: thesorrow
        comment: 'John Menerick'
        uid: 9009
        group: thesorrow
        groups: adm, docker, users, netdev, plugdev, audit, emcomm, human, defender, incidentresponse, purpleteam, redteam, blueteam, vulnmgt, disk, lp, mail, news, man, kmem, audio, dip, operator, list, irc, src, utmp, sasl, staff, systemd-journal, systemd-network, systemd-resolve, systemd-timesync, systemd-bus-proxy, kvm, crontab, syslog, fuse, bluetooth, ssl-cert, lpadmin, debian-tor, mlocate, ssh, utempter, rtkit, saned, nm-openvpn, nm-openconnect, systemd-coredump, whoopsie, landscape, epmd, sslh, _apt, dnsmasq, stunnel4, i2c, miredo, nopasswordlogin, systemd-journal-remote, smmsp, kvm, qemu, libvirt, libvirt-qemu, libvirt-dnsmasq, lxd, sddm, openbox, firewall, tap, ebf, nightmarefilesystem
        append: no
        createhome: yes
        home: /home/thesorrow
        shell: /bin/zsh
        password: "$1$PJ4PQ/fc$3RmEEGhCH9JI2LR4mWPgU/"
        expires: 1735632000
        local: yes
        seuser: human_thesorrow
        state: present
        update_password: on_create

    - name: Set SSH key for the user 'thesorrow'
      authorized_key:
        user: thesorrow
        state: present
        key: "https://raw.githubusercontent.com/w8mej/Credentials/main/Crypto/ssh_yubi.pub"
        validate_certs: "yes"
        comment: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE5qJxxYl4O5ngWxnfCMupulq7vkvdVecgFnxTiqaU4W cardno:15_260_751"

